package com.example.zeerorg.firstkotlin.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE".
*/
public class NoteDao extends AbstractDao<Note, Long> {

    public static final String TABLENAME = "NOTE";

    /**
     * Properties of entity Note.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Data = new Property(1, String.class, "data", false, "DATA");
        public final static Property Uploaded = new Property(2, boolean.class, "uploaded", false, "UPLOADED");
        public final static Property Timestamp = new Property(3, long.class, "timestamp", false, "TIMESTAMP");
        public final static Property Updated = new Property(4, boolean.class, "updated", false, "UPDATED");
        public final static Property ObjectId = new Property(5, String.class, "objectId", false, "OBJECT_ID");
    }


    public NoteDao(DaoConfig config) {
        super(config);
    }
    
    public NoteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"DATA\" TEXT NOT NULL ," + // 1: data
                "\"UPLOADED\" INTEGER NOT NULL ," + // 2: uploaded
                "\"TIMESTAMP\" INTEGER NOT NULL ," + // 3: timestamp
                "\"UPDATED\" INTEGER NOT NULL ," + // 4: updated
                "\"OBJECT_ID\" TEXT);"); // 5: objectId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Note entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getData());
        stmt.bindLong(3, entity.getUploaded() ? 1L: 0L);
        stmt.bindLong(4, entity.getTimestamp());
        stmt.bindLong(5, entity.getUpdated() ? 1L: 0L);
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(6, objectId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Note entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getData());
        stmt.bindLong(3, entity.getUploaded() ? 1L: 0L);
        stmt.bindLong(4, entity.getTimestamp());
        stmt.bindLong(5, entity.getUpdated() ? 1L: 0L);
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(6, objectId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Note readEntity(Cursor cursor, int offset) {
        Note entity = new Note( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // data
            cursor.getShort(offset + 2) != 0, // uploaded
            cursor.getLong(offset + 3), // timestamp
            cursor.getShort(offset + 4) != 0, // updated
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // objectId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Note entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setData(cursor.getString(offset + 1));
        entity.setUploaded(cursor.getShort(offset + 2) != 0);
        entity.setTimestamp(cursor.getLong(offset + 3));
        entity.setUpdated(cursor.getShort(offset + 4) != 0);
        entity.setObjectId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Note entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Note entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Note entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
